[package]
name = "platynui-cli"
version.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
platynui-runtime = { path = "../runtime" }
platynui-provider-mock = { path = "../provider-mock" }
platynui-platform-mock = { path = "../platform-mock" }
platynui-core = { path = "../core" }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
rstest = "0.26.1"
