[package]
name = "platynui-cli-bin"
version = "0.12.0-dev.3"
edition = "2024"
license = "Apache-2.0"
description = "CLI application for PlatynUI"
repository = "https://github.com/imbus/robotframework-PlatynUI"

[dependencies]
platynui-cli = { path = "../../crates/cli" }

[[bin]]
name = "platynui-cli"
path = "src/main.rs"
